version: "3"
services:
  web:
    image: htl_website:latest
    restart: unless-stopped
    ports:
      - "1680:80"
      - "16443:443"
    environment:
      - HTTP_PORT=80
      - HTTP_HOST=0.0.0.0
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    command: ["nginx", "-g", "daemon off;"]
    labels:
      - "traefik.enable=true"
      - "traefik.cms-gui.port=80"
      - "traefik.cms-gui.backend=htl_website"
      - "traefik.cms-gui.frontend.rule=Host:htlwebsite.unterrainer.at"
      - "traefik.cms-gui.frontend.entryPoints=http,https"

networks:
  default:
    name: proxy_default
